<div class="center_events_news_head cl">
	<div class="lf fl"></div>
	<div class="center_f fl"><span><?php echo $this->lang->translate('Exhibitions news');?></span></div>
	<div class="rf fl"></div>
</div>
<div class="center_events_news_content_box cl">
	<div class="center_events_news_one_row">
		<div class="center_events_news_text_box">
			<span class="date">28.07.2010</span><br/>
			<a href="#">Пресс-релиз выставки «Мир детства и школы»</a>
		</div>
	</div>
</div>