
<div style="margin-top: 50px; width: 196px; clear: both; float: none;">
    <div class="add_comp_box">
      <a href="#">Добавить компанию</a>
      <em>67584</em>&nbsp;<span>компаний в базе</span>
    </div>
    <div class="companies_index_center_top_comp_box cl">

    <div class="center_top_comp_title_box cl">
      <div class="center_top_comp_l_edge fl"></div>
      <div class="center_top_comp_title fl">Expo-advert</div>
      <div class="center_top_comp_r_edge fl"></div>
    </div>

    <div class="center_top_comp_content_box cl">
        <div class="center_top_comp_text_box fl">
          <a href="#">Эфес, ООО</a>
          <span>Запорожье / Украина</span>
        </div>
        <div class="center_top_comp_text_box fl">
          <a href="#">Дрофа-Медиа</a>
          <span>Москва / Россия</span>
        </div>
    </div>
  </div>
</div>