<div class="all_companies_client_menu_box cl">
<div class="companies_client_left_menu_mycomp cl">
    <div class="companies_client_left_menu_mycomp_title cl">
        <div class="lf fl"></div>
        <div class="center_f fl" style="width: 182px;" >
            <span>Моя компания</span>
            <div class="companies_client_left_menu_down_ico fr"></div>
        </div>
        <div class="rf fl"></div>
    </div>
    <div class="rc_t"><div class="rc_r"><div class="rc_b"><div class="rc_l">
    <div class="rc_br_trans"><div class="rc_bl_trans">
        <div class="inner_left_nav_box cl">
            <div class="companies_client_left_menu_fav_box cl">
                <div class="companies_client_left_menu_fav_left fl"></div>
                <div class="companies_client_left_menu_fav_center fl">Все избранное</div>
                <div class="companies_client_left_menu_fav_right fl"></div>
            </div>
            <div class="companies_client_left_menu_one_link_box cl">
                <a href="#">Менеджеры</a>
                <span>3 Новых</span>
                <a href="#"><div class="companies_client_left_menu_one_link_del"></div></a>
            </div>
            <hr>
            <div class="companies_client_add_box cl">
                <div class="companies_client_add_ico fl"></div>
                <a href="#">Добавить</a>
            </div>
        </div>
    </div></div></div></div>
    </div></div>
</div>
</div>