<?php
	$tabData = $this->tabsData[Init_Venues_Events::$tab_name];
	//$regions = Zend_Registry::get("regions".Tools_Events::$cacheSuffix['id']);
	$countries = Zend_Registry::get("countries".Tools_Events::$cacheSuffix['id']);
	$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
	$l = DEFAULT_LANG_CODE;
	foreach($tabData['data'] as $item){ $url="/".$l."/event/card/".$item['id']."-".Tools_View::getUrlAlias($item['brands_name'], true)."/"
?>
	<div class="events_index_item cl">
		<div class="events_index_item_title">
			<a href="<?php echo $url;?>">
				<?php echo $item['brands_name'];?>
			</a>
		</div>
		<div class="events_index_item_content_box cl">
			<div class="events_index_item_logo fl">
				<a href="<?php echo $url;?>">
					<img src="http://ws.expopromoter.com/file/event_logo.php?id=<?php echo $item['id'];?>&lang=<?php echo DEFAULT_LANG_ID;?>"/>
				</a>
			</div>
			<div class="events_index_item_content fl">
				<div class="events_index_item_info_box cl">
					<div class="events_index_item_info fl">
						<div class="events_index_item_info_date cl">
							<?php
								echo
									Tools_Events::date($l, 'd F',   strtotime($item['date_from']))
									.' &mdash; '.
									Tools_Events::date($l, 'd F Y', strtotime($item['date_to']))
									;
							?>
						</div>
						<div class="events_index_item_info_location cl">
							<?php
										echo
									$countries[$item['regions_id']][$item['countries_id']]['name']
									.', '.
									$cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name'];
								?>
						</div>
					</div>
					<?php if ($item['free_tickets']){?>
					<div class="events_index_item_free_ticket fr">
						<a href="#"><?php echo $this->lang->translate('Free ticket for buyer');?></a>
					</div>
					<?php }?>
				</div>
				<div class="events_index_item_description cl">
					<?php echo Tools_View::createShortText($item['description'], 220); ?>
				</div>
			</div>
		</div>
	</div>
<?php
	}
?>
<div class="paginator cl">
<?php
	echo Tools_View::getPages(
	array(
		'url'=>Tools_View::setUrlByTemplate(
			array(
				'url'=>$this->requestUri,
				'template'=>DEFAULT_ROUTE,
			),
			array(
				'tab'=>Init_Venues_Events::$tab_name,
				'tab_action'=>'page',
			)
		),
		'template'=>DEFAULT_ROUTE,
	),
	$this->tabsData[Init_Venues_Events::$tab_name]['array_pages'],
	'tab_id',
	array(
		'urlFunctionName'=>'setUrlByTemplate',
		'linkTag'=>array('start'=>'<div class="one_page fl">', 'end'=>'</div>'),
		'selectedTag'=>array('start'=>'<div class="one_page selected fl">', 'end'=>'</div>'),
		'first'=>false, 'prev'=>false, 'next'=>false, 'last'=>false,
	)
);
	?>
</div>