<div class="ec_tabs_body_box cl">
	<div class="cl" id="ec_tabs">
		<ul>
			<?php
			$tabsContent = '';
			foreach ($this->layoutsData['extra']['extra_events_companies_tabs_box'] as $tab_id=>$tab_data){
				$tabsContent .= '<div class="ec_tab_box ec_'.$tab_id.'_tab" id="ec_tab_'.$tab_id.'">'.$this->render('inc/extra/events_companies_tabs/'.$tab_id.'.phtml').'</div>';
			?>
				<li class="tab_title_<?php echo $tab_id;?>"><a href="#ec_tab_<?php echo $tab_id;?>"><?php echo $tab_data['title'];?></a></li>
			<?php
			}
			?>
		</ul>
		<?php echo $tabsContent; ?>
	</div>
</div>
<script type="text/javascript">
	$(function() {
		$('#ec_tabs').tabs();
	});
</script>
