<div class="rc_t extra_products_inner_content"><div class="rc_r"><div class="rc_b"><div class="rc_l">
	<div class="rc_tl"><div class="rc_tr"><div class="rc_br"><div class="rc_bl">
		<div class="extra_products_box cr">
			<div class="extra_products_title cl">
				<span>Товары и услуги компаний</span>
				<input type="image" src="/img/index/btn_l.png"/>
				<input type="image" src="/img/index/btn_r.png"/>
				<em>1 из 2</em>
			</div>
		</div>
		<div class="extra_products_images_box cr">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">

			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
			<img src="/img/index/test1.png">
		</div>
	</div></div></div></div>
</div></div></div></div>