<div class="right_advert_head cl">
	<div class="lf fl"></div>
	<div class="center_f fl" style="width: 238px;"><span><?php echo $this->lang->translate("ExpoAdvert");?></span></div>
	<div class="rf fl"></div>
</div>
<div class="right_advert_content_box cl">
	<?php foreach ($this->layoutsData['right']['right_banners_advert_box'] as $item){ $url = Tools_Banner::getClickerUrl($item['id'], $item, 1);?>
	<div class="right_advert_one_row cl">
		<a href="<?php echo $url;?>">
			<img src="<?php echo ($item['bt']=='normal'?PATH_DATA_PBLBANNERS:PATH_DATA_PBLGAGBANNERS).$item['file_name'];?>">
		</a>
		<div class="right_advert_text_box">
			<a href="<?php echo $url;?>"><?php echo $item['file_alt']; ?></a>
			<span class="text cl">
				<a href="<?php echo $url;?>">
					<?php echo $item['text_content']; ?>
				</a>
			</span>
		</div>
	</div>
	<?php } ?>
	<div align="center" style="padding: 5px;">
		<a href="http://www.expopromoter.com/Static/lang/en/page/registration/type/advertiser/"><?php echo $this->lang->translate("add an ad");?></a>&nbsp;|&nbsp;<a href="http://www.expopromoter.com/Static/lang/en/page/registration/type/webPartner/"><?php echo $this->lang->translate("become a partner");?></a>
	</div>
</div>
