<?php
	$l = $this->lang->getLocale();
	$cache = Zend_Registry::get('categories'.Tools_Events::$cacheSuffix['id']);
?>
<?php foreach($this->layoutsData['extra']['extra_events_companies_tabs_box']['companies']['data'] as $category){ ?>
<div class="lnk cl">
	<a href="/<?php echo $l; ?>/companies/search/region-europe/country-ukraine/category-<?php echo $cache[$category['brands_categories_id']]['alias']; ?>/"><?php echo $category['name'];?></a> <em>(<?php echo $category['c'];?>)</em>
</div>
<?php } ?>