<?php
	$l = DEFAULT_LANG_CODE;
	$cache = Zend_Registry::get('categories'.Tools_Events::$cacheSuffix['id']);
?>
<?php foreach($this->layoutsData['extra']['extra_events_companies_tabs_box']['companies']['data'] as $category){ ?>
<div class="lnk cl">
	<a href="<?php echo "/".$l."/companies/search/".DEFAULT_SEARCH."category-".$cache[$category['brands_categories_id']]['alias']."/"; ?>"><?php echo $category['name'];?></a> <em>(<?php echo $category['c'];?>)</em>
</div>
<?php } ?>