<?php /*
	<div class="boxes cl">
		<div class="one_box cl">
			<div class="lb fl"></div>
			<div class="box_content fl">
				<div class="box_content_left_col fl">
					<div class="title cl">Здравоохронение</div>
					<div class="date cl">01 мая — 31 октября 2010</div>
				</div>
				<div class="box_content_right_col fr">
					<div class="city cl">Украина, Одесса</div>
					<a href="#">в избранное</a>
				</div>
			</div>
			<div class="rb fl"></div>
		</div>
	</div>
*/ ?>