<div class="card_one_hostel_tab fl">
	<img src="/img/card/test.png">
	<div class="card_hostel_tab_desc_box fl">
		<div class="card_hostel_name cl">
			<a href="#">Fast Food – Индустрия быстрого питания</a>
		</div>
		<div class="card_hostel_address cl">м. Львів, Проспект Свободи, 45</div>
		<a href="#"><div class="contents_btn cl"></div></a>
		<span>Цена проживания за сутки: </span><div class="clr"></div>
		<span>мин: &nbsp;</span><span style="color: #dd5500">800.00 (грн.)</span><div class="clr"></div>
		<span>макс:&nbsp; </span><span style="color: #dd5500">2250.00 (грн.) </span>
	</div>
</div>

<div class="card_one_hostel_tab fl">
	<img src="/img/card/test.png">
	<div class="card_hostel_tab_desc_box fl">
		<div class="card_hostel_name cl">
			<a href="#">Fast Food – Индустрия быстрого питания</a>
		</div>
		<div class="card_hostel_address cl">м. Львів, Проспект Свободи, 45</div>
		<a href="#"><div class="contents_btn cl"></div></a>
		<span>Цена проживания за сутки: </span><div class="clr"></div>
		<span>мин: &nbsp;</span><span style="color: #dd5500">800.00 (грн.)</span><div class="clr"></div>
		<span>макс:&nbsp; </span><span style="color: #dd5500">2250.00 (грн.) </span>
	</div>
</div>

<div class="card_one_hostel_tab fl">
	<img src="/img/card/test.png">
	<div class="card_hostel_tab_desc_box fl">
		<div class="card_hostel_name cl">
			<a href="#">Fast Food – Индустрия быстрого питания</a>
		</div>
		<div class="card_hostel_address cl">м. Львів, Проспект Свободи, 45</div>
		<a href="#"><div class="contents_btn cl"></div></a>
		<span>Цена проживания за сутки: </span><div class="clr"></div>
		<span>мин: &nbsp;</span><span style="color: #dd5500">800.00 (грн.)</span><div class="clr"></div>
		<span>макс:&nbsp; </span><span style="color: #dd5500">2250.00 (грн.) </span>
	</div>
</div>