<div class="all_companies_client_anons_box cl">
    <div class="companies_client_add_box cl">
        <div class="fr">
            <div class="companies_client_add_ico fl"></div>
            <a href="#">Добавить анонс участия</a>
        </div>
    </div>
    
    <div class="companies_client_anons_control_box cl">
        <input type="checkbox">
        <select>
            <option>удалить нах</option>
        </select>
    </div>
    <div class="companies_client_one_anons_box cl companies_client_anons_box_vip">
        <div class="companies_client_one_anons_box_title cl">
            <a href="#">Animal Farming</a>
        </div>
        <div class="companies_client_one_anons_box_info cl">
            <div class="companies_client_one_anons_box_info_left_col fl">
                <input type="checkbox">
            </div>
            <div class="companies_client_one_anons_box_info_center_col fl">
                <div class="companies_client_one_anons_box_info_center_col_one_row cl">
                    <div class="field_name fl">Дата:</div>
                    <div class="value fl" style="font-weight:bold;">Дата:</div>
                </div>
                <div class="companies_client_one_anons_box_info_center_col_one_row cl">
                    <div class="field_name fl">Страна: </div>
                    <div class="value fl">Кувейт, Сафат</div>
                </div>
                <div class="companies_client_one_anons_box_info_center_col_one_row cl">
                    <div class="field_name fl">Номер стенда:</div>
                    <div class="value fl" >26</div>
                </div>
            </div>
            <div class="companies_client_one_anons_box_info_right_col fl">
                <a href="#">Редактировать</a>
                <a href="#">Удалить</a>
            </div>
        </div>
    </div>
</div>