<div class="all_companies_client_news_box cl">
    <div class="companies_client_add_box cl">
        <div class="fr">
            <div class="companies_client_add_ico fl"></div>
            <a href="#">Добавить новость</a>
        </div>
    </div>

    <div class="companies_client_news_control_box cl">
        <input type="checkbox">
        <select>
            <option>удалить нах</option>
        </select>
    </div>
    <div class="companies_client_one_news_box cl">
        <div class="companies_client_one_news_box_public cl">
            Опубликовано: 21/09/2010
        </div>
        <div class="companies_client_one_news_box_info cl">
            <div class="companies_client_one_news_box_info_left_col fl">
                <input type="checkbox">
            </div>
            <div class="companies_client_one_news_box_info_text_col fl">
                На выставке-форуме будут представлены ведущие строительные, инвестиционные, банки, риэлторские объединения и агентства, юридические фирмы, наиболее активно в этом году представлены объекты недвижимости за рубежом  Испании, Болгарии, Кипра, Турции, Италии, Таиланда, Греции, Египта, Литвы, Доминиканы, IШвейцарии, др. 
            </div>
        </div>
        <div class="companies_client_one_news_box_info_right_col fr">
            <a href="#">Редактировать</a>
            <a href="#">Удалить</a>
        </div>
    </div>
</div>