<div class="body_events_accordion_box cl">
	<div class="title_box cl">
		<div class="text fl">Ближайшие выставки</div>
		<div class="lnk fl">
			<a href="#">Календарь выставок</a>
		</div>
		<div class="add fl">
			<a href="#">Добавить выстаку</a>
		</div>
	</div>
	<div class="body_events_accordion_content cl">
		<div class="accordion_title_box cl">
			<div class="title cl">Эффективное животноводство</div>
			<div class="date cl">01 мая — 31 октября 2010</div>
			<div class="desc cl">Украина, Одесса</div>
		</div>
		<img src="/img/index/test.png">
	</div>
</div>