<?php
	//$regions = Zend_Registry::get("regions".Tools_Events::$cacheSuffix['id']);
	$countries = Zend_Registry::get("countries".Tools_Events::$cacheSuffix['id']);
	$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
	$l = DEFAULT_LANG_CODE;
?>
<div class="body_events_accordion_content cl">
<?php foreach ($this->layoutsData['body']['body_events_accordion_box']['data'] as $item){ $url=Tools_Banner::getClickerUrl($item['bannerData']['id'], $item);?>
	<h3>
		<div class="body_events_accordion_boxes cl">
			<div class="body_events_accordion_one_box cl">
				<div class="body_events_accordion_box_content fl">
					<div class="body_events_accordion_box_content_left_col fl">
						<div class="title cl"><a href="<?php echo $url; ?>"><?php echo $item['brands_name']; ?></a></div>
						<div class="date cl">
							<?php
								echo
								Tools_Events::date($l, 'd F',   strtotime($item['date_from']))
								.' &mdash; '.
								Tools_Events::date($l, 'd F Y', strtotime($item['date_to']))
								;
							?>
						</div>
					</div>
					<div class="body_events_accordion_box_content_right_col fr">
						<div class="city cl">
							<?php
								echo
								$countries[$item['regions_id']][$item['countries_id']]['name']
								.', '.
								$cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name'];
							?>
						</div>
						<?php /* <a href="#"><?php echo $this->lang->translate("add to favorites"); ?></a> */ ?>
					</div>
				</div>
			</div>
		</div>
	</h3>
	<div class="accordion_body">
		<a href="<?php echo $url; ?>"><img alt="<?php echo $item['bannerData']['file_alt'];?>" src="<?php echo ADMIN_HOST_NAME."/data/images/banners/".$item['bannerData']['file_name'];?>"></a>
		<div class="accordion_title_box cl">
			<div class="title cl"><a href="<?php echo $url; ?>"><?php echo $item['brands_name']; ?></a></div>
			<div class="date cl">
				<?php
					echo
					Tools_Events::date($l, 'd F',   strtotime($item['date_from']))
					.' &mdash; '.
					Tools_Events::date($l, 'd F Y', strtotime($item['date_to']))
					;
				?>
			</div>
			<div class="desc cl">
				<?php
					echo
					$countries[$item['regions_id']][$item['countries_id']]['name']
					.', '.
					$cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name'];
				?>
			</div>
			<div class="desc cl">
				<a href="<?php echo $url; ?>"><?php echo Tools_View::createShortText($item['description'], 220); ?></a>
			</div>
		</div>
	</div>
<?php } ?>
</div>
