<div class="body_events_accordion_box cl">
	<div class="title_box cl">
		<div class="text fl">Ближайшие выставки</div>
		<div class="lnk fl">
			<a href="#">Календарь выставок</a>
		</div>
		<div class="add fl">
			<a href="#">Добавить выстаку</a>
		</div>
	</div>
	<div class="body_events_accordion_content cl">
		<h3>
			<div class="body_events_accordion_boxes cl">
				<div class="body_events_accordion_one_box cl">
					<div class="body_events_accordion_box_content fl">
						<div class="body_events_accordion_box_content_left_col fl">
							<div class="title cl">Здравоохронение</div>
							<div class="date cl">01 мая — 31 октября 2010</div>
						</div>
						<div class="body_events_accordion_box_content_right_col fr">
							<div class="city cl">Украина, Одесса</div>
							<a href="#">в избранное</a>
						</div>
					</div>
				</div>
			</div>
		</h3>
		<div>
			<img src="/img/index/test.png">
		</div>

		<h3>
			<div class="accordion_title_box cl">
				<div class="title cl">Эффективное животноводство</div>
				<div class="date cl">01 мая — 31 октября 2010</div>
				<div class="desc cl">Украина, Одесса</div>
			</div>
		</h3>
		<div>
			<img src="/img/index/test.png">
		</div>

		<h3>
			<div class="accordion_title_box cl">
				<div class="title cl">Эффективное животноводство</div>
				<div class="date cl">01 мая — 31 октября 2010</div>
				<div class="desc cl">Украина, Одесса</div>
			</div>
		</h3>
		<div>
			<img src="/img/index/test.png">
		</div>
	</div>
</div>