<?php
	//$regions = Zend_Registry::get("regions".Tools_Events::$cacheSuffix['id']);
	//$countries = Zend_Registry::get("countries".Tools_Events::$cacheSuffix['id']);
	//$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
	$l = DEFAULT_LANG_CODE;
?>
<div class="body_events_title_content">
	<div class="text fl"><?php echo $this->lang->translate('Upcoming events'); ?></div>
	<div class="add fr">
		<a href="http://event.expopromoter.com/<?php echo $l ?>/"><?php echo $this->lang->translate("Add new exhibition"); ?></a>
	</div>
	<div class="lnk fr">
		<a href="<?php echo '/'.$l.'/events/'.DEFAULT_SEARCH;?>"><?php echo $this->lang->translate("Exhibition's calendar"); ?></a>
	</div>
</div>
