<?php
	$l = DEFAULT_LANG_CODE;
	$onPage = 8;
	$c = count($this->layoutsData['body']['body_companies_goods_box']['data']);
?>
<div class="rc_t body_products_inner_content"><div class="rc_r"><div class="rc_b"><div class="rc_l">
	<div class="rc_tl"><div class="rc_tr"><div class="rc_br"><div class="rc_bl">
		<div class="body_products_box cl">
			<div class="body_products_title cl">
				<span><?php echo $this->lang->translate('Products and services'); ?></span>
				<a class="body_products_prev">&nbsp;</a>
				<a class="body_products_next">&nbsp;</a>
				<em>1</em><?php echo '<em>'.$this->lang->translate('of').'</em><em>'.ceil($c/$onPage).'</em>';?>
			</div>
		</div>
		<div class="scrollable body_products_body">
			<div class="items body_products_images_box cl">
				<div class="page">
<?php
	$i=0;
	foreach ($this->layoutsData['body']['body_companies_goods_box']['data'] as $item){ $link = '/'.$l.'/companies/card/'.$item['companies_id'].'/'.Init_Companies_Services::$tab_name.'/card/'.$item['id'].'/';
?>
	<div class="body_products_one_box fl">
		<div class="body_products_image_box cl">
			<a href="<?php echo $link; ?>">
				<img src="http://admin.expopromoter.com/data/images/companies/<?php echo $item['companies_id']; ?>/services/logo/<?php echo $item['id'];?>.jpg">
			</a>
		</div>
		<div class="body_products_title_box cl">
			<a href="<?php echo $link; ?>">
				<?php echo $item['name'];?>
			</a>
		</div>
	</div>
<?php
		$i++;
		if($i%$onPage==0 && $i!=$c){
?>
				</div>
				<div class="page">
<?php
		}
	}
?>
				</div>
			</div>
		</div>
	</div></div></div></div>
</div></div></div></div>
