<div class="companies_register_all_box cl">
    <div class="companies_register_title cl">Регистрация нового пользователя</div>
    <div class="companies_register_main_box cl">
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Логин:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Пароль:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Подверждение пароля:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Язык</div>
            <div class="companies_register_main_box_radio fl">
                <span>English</span>
                <input type="radio">
                <span>Русский</span>
                <input type="radio">
            </div>
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Фамилия:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Имя, Отчество:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">E-Mail:</div>
            <input type="text">
        </div>
    </div>

    <div class="companies_register_main_box cl">
        <div class="companies_register_title cl">Данные о компании:</div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">&nbsp;</div>
            <div class="companies_register_main_box_one_row_lnks fl">
                <a href="#">+&nbsp;<span class="bottom_dashed">Добавить компанию</span></a>
                <a href="#">+&nbsp;<span class="bottom_dashed">Присоединиться к существующей</span></a>
            </div>
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Компания:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Страна:</div>
            <select>
                <option>- выберите страну</option>
            </select>
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Город:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Почтовый индекс:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Почтовый адрес:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Телефоны / факсы:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">E-mail:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Адрес веб-сайта:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Описание деятельности компании:</div>
            <textarea cols="56" rows="10">

            </textarea>
        </div>
        <div class="companies_register_main_box_one_row cl" style="margin-top: 10px;">
            <div class="companies_register_main_box_text_val fl">&nbsp;</div>
            <div class="companies_register_main_box_one_row_lnks fl">
                <a href="#"><span class="bottom_dashed">Статус посетителя выставки</span></a>
            </div>
        </div>
        <div class="companies_register_main_box_one_row_span cl">Заполняется для получения бесплатных пригласительных</div>
        <div class="companies_register_main_box_one_row_photo cl" >
            <div class="companies_register_main_box_text_val fl">Фото:</div>
            <input type="text" id="input_form">
            <input type="button" id="input_btn" value="Обзор">
        </div>
        <div class="companies_register_main_box_one_row_span cl">
                Внимание! Бесплатный пропуск на выставку осуществляется по фотографии. Размер загружаемого файла (фотографии) не должен превышать 300 Кб.
        </div>
        <div class="companies_register_main_box_one_row cl" style="margin-top: 10px;">
            <div class="companies_register_main_box_text_val fl">Должность:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Положение:</div>
            <input type="text">
        </div>
        <div class="companies_register_main_box_one_row cl">
            <div class="companies_register_main_box_text_val fl">Выполняемые функции:</div>
            <div class="companies_register_main_box_checkbox_box fl">
                <hr>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Менеджмент, руководство</span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Проектирование, разработки </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Информационные системы </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Образование </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Реклама, маркетинг  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Cбыт, продажи  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Образование </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Делопроизводство, кадры  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Производство, технологический процесс  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Техническое обслуживание  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Логистика  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Закупки, снабжение </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Прочее  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Автоматизация производства  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Телекоммуникации, связь  </span>
                </div>
                <div class="companies_register_main_box_one_checkbox_row cl">
                    <input type="checkbox">
                    <span>Безопасность</span>
                </div>
            </div>
        </div>
    </div>
    <center><input class="big_submit_button" type="button" value="Зарегестрировать"></center>
</div>