<div class="tour_order_top_info_box cl">
    <div class="tour_order_top_info_text_box cl">
        Внимание! Заполнение и отправка нам данной анкеты не влечет за собой каких-либо финансовых обязательств с Вашей стороны и носит характер предварительного запроса.
        <br><br>
        Внимание! Наличие ошибок в полях с контактной информацией сделает невозможным контакт с Вами.
    </div>
</div>
<div class="tour_order_step_title cl">1. Выберите туристическую компанию</div>
<div class="tour_order_operators_box cl">
    <div class="tour_order_one_operator_box cl">
        <input type="checkbox">
        <a href="#">Туроператор ЦМС «Оптима»</a>
        <span>Украина, Киев </span>
    </div>
    <div class="tour_order_one_operator_box sel cl">
        <input type="checkbox">
        <a href="#">Туристическая компания «Битско»</a>
        <span>Украина, Киев </span>
    </div>
    <div class="tour_order_one_operator_box cl">
        <input type="checkbox">
        <a href="#">Альбатрос-Тревел, Оператор Делового туризма</a>
        <span>Украина, Киев </span>
    </div>
</div>
<div class="tour_order_tour_data_box cl">
    <div class="tour_order_tour_data_inner_box cl">
        <div class="tour_order_step_title cl">2. Данные о поездке:</div>
    </div>
    <div class="tour_order_tour_data_dest_box">
        <div class="tour_order_tour_data_inner_title cl">Место назначения</div>
        <div class="tour_order_tour_data_dest cl">
            <span>Cтрана</span>
            <select>
                <option>-выбирете страну</option>
            </select>
            <span>Город</span>
            <input type="text">
        </div>
    </div>
    <div class="tour_order_tour_data_params_box cl">
        <div class="tour_order_tour_data_params_date fl">
            <div class="tour_order_tour_data_inner_title cl">Календарь</div>
            <input type="text">
            <input type="text">
        </div>
        <div class="tour_order_tour_data_params_count fl">
            <div class="tour_order_tour_data_inner_title cl">Количество</div>
            <span>Человек</span><input type="text">
            <span>Номеров</span><input type="text">
        </div>
        <div class="tour_order_tour_data_params_stars fl">
            <div class="tour_order_tour_data_inner_title cl">Звезд</div>
            <img src="/img/client/hotel_star.png">
            <img src="/img/client/hotel_star.png">
            <img src="/img/client/hotel_star.png">
            <img src="/img/client/hotel_empty_star.png">
            <img src="/img/client/hotel_empty_star.png">
            <span>Человек</span>
        </div>
        <div class="tour_order_tour_data_params_cat fl">
            <div class="tour_order_tour_data_inner_title cl">Категория номера</div>
            <div class="tour_order_tour_data_params_cat_row cl">
                <input type="checkbox"><span>SGL</span>
            </div>
            <div class="tour_order_tour_data_params_cat_row cl">
                <input type="checkbox"><span>DBL</span>
            </div>
            <div class="tour_order_tour_data_params_cat_row cl">
                <input type="checkbox"><span>TRPL</span>
            </div>
        </div>
    </div>
    <div class="tour_order_tour_data_adv_params_box cl">
        <div class="tour_order_tour_data_adv_params_col fl">
            <div class="tour_order_tour_data_inner_title cl">Дополнительно</div>
            <div class="tour_order_tour_data_adv_params_col_row cl">
                <input type="checkbox">
                <span>Трансферт</span>
            </div>
            <div class="tour_order_tour_data_adv_params_col_row cl">
                <input type="checkbox">
                <span>Оформление визы</span>
            </div>
        </div>
        <div class="tour_order_tour_data_adv_params_col fl">
            <div class="tour_order_tour_data_inner_title cl">Дополнительно</div>
            <div class="tour_order_tour_data_adv_params_col_row cl">
                <input type="checkbox">
                <span>Трансферт</span>
            </div>
            <div class="tour_order_tour_data_adv_params_col_row cl">
                <input type="checkbox">
                <span>Оформление визы</span>
            </div>
        </div>
        <div class="tour_order_tour_data_adv_params_col fl">
            <div class="tour_order_tour_data_inner_title cl">Дополнительно</div>
            <div class="tour_order_tour_data_adv_params_col_row cl">
                <input type="checkbox">
                <span>Трансферт</span>
            </div>
            <div class="tour_order_tour_data_adv_params_col_row cl">
                <input type="checkbox">
                <span>Оформление визы</span>
            </div>
        </div>
    </div>
</div>
<div class="tour_order_tour_data_box cl">
    <div class="tour_order_tour_data_inner_box cl">
        <div class="tour_order_step_title cl">3. Ваши контактные данные:</div>
    </div>
    <div class="tour_order_tour_contact_form_box cl">
        <div class="tour_order_tour_contact_form_left_col fl">
            <div class="tour_order_tour_contact_form_left_col_row cl">
                <span>Страна<em>*</em>:</span>
                <select>
                    <option></option>
                </select>
            </div>
            <div class="tour_order_tour_contact_form_left_col_row cl">
                <span>Компания<em>*</em>:</span>
                <input type="text">
            </div>
            <div class="tour_order_tour_contact_form_left_col_row cl">
                <span>Имя<em>*</em>:</span>
                <input type="text">
            </div>
            <div class="tour_order_tour_contact_form_left_col_row cl">
                <span>Телефон<em>*</em>:</span>
                <input type="text">
            </div>
            <div class="tour_order_tour_contact_form_left_col_row cl">
                <span>Город<em>*</em>:</span>
                <input type="text">
            </div>
            <div class="tour_order_tour_contact_form_left_col_row cl">
                <span>E-mail<em>*</em>:</span>
                <input type="text">
            </div>
        </div>
         <div class="tour_order_tour_contact_form_left_col fl" style="margin-left: 50px;">
            <div class="tour_order_tour_contact_form_left_col_row cl">
                <span>Дополнительно:</span>
                <textarea></textarea>
            </div>
         </div>
    </div>
</div>
    <center><input type="button" value="Отправить" id="sbmbtn"></center>

