<div class="add_about_company_box cl">
    <div class="add_about_company_inner_box cl">
        <div class="add_about_company_inner_title cl">Информация о компании</div>
        <div class="add_about_company_inner_box_text cl">
            <span>Название<em>*</em>:</span>
        </div>
        <input type="text" class="add_about_company_input_big cl">
        <div class="add_about_company_logo_box cl">
            <img src="/img/companies/test_img.png">
            <div class="add_about_company_logo_text_box fl">
                <div class="add_about_company_inner_box_text cl">
                    <span>Загрузить лого</span>
                </div>
                <div class="add_about_company_logo_input_box cl">
                    <input type="text" class="input_text fl">
                    <input type="button" value="Обзор" class="input_button fl">
                </div>
            </div>
        </div>
        <div class="add_about_company_inner_box_text cl">
            <span>Категория<em>*</em>:</span>
        </div>
        <select class="add_about_company_input_middle cl">
        </select>
        <div class="add_about_company_inner_box_text cl">
            <span>Страна<em>*</em>:</span>
        </div>
        <select class="add_about_company_input_middle cl">
        </select>
        <div class="add_about_company_inner_box_text cl">
            <span>Город:</span>
        </div>
        <input type="text" class="add_about_company_input_middle cl">
        <div class="add_about_company_inner_box_text cl">
            <span>Индекс:</span>
        </div>
        <input type="text" class="add_about_company_input_small cl" style="width: 170px;">
        <div class="add_about_company_inner_box_text cl">
            <span>Электронныая почта: </span>
        </div>
        <input type="text" class="add_about_company_input_small cl">
        <div class="add_about_company_inner_box_text cl">
            <span>Веб-сайт:</span>
        </div>
        <input type="text" class="add_about_company_input_small cl">
        <div class="add_about_company_inner_box_text cl">
            <span>Телефон:</span>
        </div>
        <input type="text" class="add_about_company_input_small cl">
        <div class="add_about_company_inner_box_text cl">
            <span>Факс:</span>
        </div>
        <input type="text" class="add_about_company_input_small cl">
        <div class="add_about_company_inner_box_text cl">
            <span>Описание:</span>
        </div>
        <textarea></textarea>
    </div>
</div>
<div class="add_about_company_box cl">
    <div class="add_about_company_inner_box cl">
        <div class="add_about_company_inner_title cl">English version</div>
        <div class="add_about_company_inner_box_text cl">
            <span>Name<em>*</em>:</span>
        </div>
        <input type="text" class="add_about_company_input_big cl">
        <div class="add_about_company_inner_box_text cl">
            <span>Сompany description<em>*</em>:</span>
        </div>
        <textarea></textarea>
        <div class="add_about_company_inner_box_text cl">
            <span>Address<em>*</em>:</span>
        </div>
        <textarea></textarea>
    </div>
</div>
<center><input type="button" value="Отправить" id="about_sbmt"></center>