<?php
	$item = $this->data;
	$regions = Zend_Registry::get("regions".Tools_Events::$cacheSuffix['id']);
	$countries = Zend_Registry::get("countries".Tools_Events::$cacheSuffix['id']);
	$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
	$l = DEFAULT_LANG_CODE;
	$link = '/'.$l.'/';
	$t = time();
	if ($t>strtotime($item['date_to'].' 23:59:59')){
		$period = $this->lang->translate('The exhibition has been already closed');
	}
	elseif ($t<strtotime($item['date_from'].' 00:00:00')){
		$period = $this->lang->translate('The exhibition is not opened yet');
	}
	else{
		$period = $this->lang->translate('The exhibition is opened now');
	}
?>
<div class="all_card_content_box cl">
<div class="card_crumbs cl">
	<?php $link.='events/'; $name=$this->lang->translate('Exhibitions');?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>&nbsp;&rarr;&nbsp;
	<?php $link.='region-europe/'; $name=$regions[$item['regions_id']]['name'];?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>&nbsp;&rarr;&nbsp;
	<?php $link.='country-ukraine/'; $name=$countries[$item['regions_id']][$item['countries_id']]['name'];?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>&nbsp;&rarr;&nbsp;
	<?php $link.='city-kiev/'; $name=$cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name'];?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>&nbsp;&rarr;&nbsp;
	<?php $link='/'.$l.'/event/card/'.$item['id'].'-'.Tools_View::getUrlAlias($item['brands_name'], true).'/'; $name=$item['brands_name']; ?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>
	<?php $this->data['link'] = $link; ?>
</div>
<div class="card_desc_box cl">
<div class="left_col fl">
	<div class="card_title_box cl">
		<span><?php echo $item['brands_name'];?></span>
		<?php /*
		<div class="fav_ico fl"></div>
		<a href="#">в избранное</a>
 		*/?>
	</div>
	<div class="card_main_info cb">
		<img src="http://admin.expopromoter.com/data/images/events/logo/<?php echo DEFAULT_LANG_ID.'/'.$item['id'];?>.jpg">
		<div class="card_main_info_desc fl">
			<div class="span_box cb">
				<span><?php echo $period;?></span>
			</div>
			<div class="date">
			<?php
				echo
					Tools_Events::date($l, 'd F',   strtotime($item['date_from']))
					.' &mdash; '.
					Tools_Events::date($l, 'd F Y', strtotime($item['date_to']));
			?>
			</div>
			<div class="place">
			<?php
				echo
					$countries[$item['regions_id']][$item['countries_id']]['name']
					.', '.
					$cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name'];
			?>
			</div>
			<div class="span_box cb" style="margin-top: 15px;">
				<span><?php echo $this->lang->translate('Frequency');?>:&nbsp;</span><span style="color: #333333;"><?php echo $item['period'];?></span>
			</div>
			<div class="span_box cb">
				<span><?php echo $this->lang->translate('Venue');?>:&nbsp; </span><a href="<?php echo '/'.$l.'/venues/card/'.$item['expocenter_id'].'-'.Tools_View::getUrlAlias($item['expocenter'], true).'/'; ?>"><?php echo $item['expocenter'];?></a>
			</div>
			<div class="span_box cb">
				<span><?php echo $this->lang->translate('Organizer');?>: &nbsp;</span><a href="#"><?php echo $item['organizer'];?></a>
			</div>
		</div>
	</div>
</div>

<div class="right_col fr">
	<div class="card_tabs_box cl">
		<div class="tabs cl">
			<div class="right_tab fl">
				<div class="tab_left fl"></div>
				<div class="tab_center fl" style="border-bottom: 0 !important;">Описание</div>
				<div class="tab_right fl"></div>
			</div>
		</div>
		<div class="card_right_tabs_body_box cl">
			<div class="box visible">
				<div class="card_right_tab_row cb">
					<div class="take_part fl"></div>
					<a href="#">Участие в выставке</a>
				</div>
				<div class="card_right_tab_row cb">
					<div class="tiket fl"></div>
					<a href="#">Билет на выставку</a>
				</div>
				<div class="card_right_tab_row cb">
					<div class="business_tour fl"></div>
					<a href="#">Бизнес-тур</a>
				</div>
				<div class="card_right_tab_row cb">
					<div class="aero_tiket fl"></div>
					<a href="#">Авиобилет</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="subscribe_box cl">
	<div class="left_border fl"></div>
	<div class="body_center fl">
		<input type = "checkbox"><span><?php echo $this->lang->translate('Remind me about this event');?></span>
		<input type = "checkbox" style="margin-left: 30px;"><span><?php echo $this->lang->translate('Notify me if any info on this exhibition is changed');?></span>
		<div class="body_right_btn fr">
			<input src="/img/card/okay_btn.png" type="image">
		</div>
		<div class="body_right_field fr">
			<input type = "text">
		</div>
	</div>
	<div class="right_border fl"></div>
</div>

<div class="card_tabs_box cl">
<div class="cl" id="tabs">
	<ul>
		<?php
			$tabsContent = '';
			$activeTabId = false;
			$tabIndex = 0;
			foreach ($this->tabsData as $tab_id=>$tab_data){
				if (!$tab_data['data']) continue;
				if ($tab_data['active']) $activeTabId = $tabIndex;
				$tabsContent .= '<div class="card_card_tab_box card_'.$tab_id.'_tab" id="'.$tab_id.'">'.$this->render('/event/tabs/'.$tab_id.'.phtml').'</div>';
		?>
			<li class="tab_title_<?php echo $tab_id;?>"><a href="#<?php echo $tab_id;?>"><?php echo $tab_data['title'];?></a></li>
		<?php
				$tabIndex++;
			}
		?>
	</ul>
	<?php echo $tabsContent; ?>
</div>
</div>
<script type="text/javascript">
	$(function() {
		$('#tabs').tabs(<?php echo $activeTabId?'{"selected":'.$activeTabId.'}':'';?>);
	});
</script>
</div>
</div>
<?php /*
<div class="card_title_box cl">Где остановится? Expoua.com рекомендует:</div>
<div class="recommendation_box cl">
	<?php for($i=0; $i<6; $i++) {?>
	<div class="one_recommendation_box fl">
		<img src="/img/card/test.png">
		<a href="#">Опера Готель</a>
	</div>
	<?php } ?>
</div>
*/ ?>
