<?php
	if ($this->activeMenu){
	foreach ($this->menuLinks[$this->activeMenu]['submenu'] as $menu=>$menuLink){
?>
<div class="sub_menu_item<?php echo $this->activeSubmenu==$menu?' selected':'';?>">
	<a href="<?php echo $menuLink['url'];?>" title="<?php echo $this->lang->translate($menuLink['title']);?>"><?php echo $this->lang->translate($menuLink['title']);?></a>
</div>
<?php } ?>
<script type="text/javascript">
	var activeSubMenu = activeSubMenu || false;
	activeSubMenu = <?php echo $this->activeSubmenu?"'".$this->activeSubmenu."'":'false';?>;
</script>
<?php } ?>