<div class="user_buttons_box">
	<div class="user_button_logon">
		<a href="#"><?php echo $this->lang->translate('Login');?></a>
	</div>
	<div class="user_button_reg">
		<a href="#"><?php echo $this->lang->translate('Registration');?></a>
	</div>
</div>
<div class="user_links_box">
	<div class="user_link_subscribe">
		<a href="#"><?php echo $this->lang->translate('Subscribe');?></a>
	</div>
	<?php /*
	<div class="user_links">
		<div class="user_link_favorites">
			<a href="#">{#jsonFavorites#}</a> (0)
		</div>
		<div class="user_link_save">
			<a href="#">{#jsonSave#}</a>
		</div>
	</div>
 	*/ ?>
</div>