<div class="all_footer_box cl">
	<div class="footer_inner_box cl">
		<div class="footer_one_column fl">
			<span>2002–2009 © ExpoPromoGroup</span>
			<a href="#">О проекте, контакты</a>
			<a href="#">info@expoua.com</a>
		</div>
		<div class="footer_one_column fl">
			<span>Проекты компании ExpoPromoGroup:</span>
			<a href="#">Выставки и ярмарки в мире</a>
			<a href="#">Выставки России</a>
			<a href="#">Выставки в США</a>
			<a href="#">Выставки в Великобритании</a>
		</div>
		<div class="footer_one_column fl">
			<span>Туристические партнеры выставочного веб-портала www.ExpoUA.com:</span>
			<a href="#">Туроператор ЦМС Оптима</a>
			<a href="#">BTL - Business Travel Leisure</a>
			<a href="#">Туркомпания Битско</a>
		</div>
		<div class="footer_one_column fl">
			<span>Наши услуги:</span>
			<a href="#">Участникам выставок</a>
			<a href="#">Организаторам выставок </a>
			<a href="#">Сервисным компаниям</a>
			<a href="#">Туристическим компаниям</a>
			<a href="#">Рекламодателям</a>
			<a href="#">Веб-партнерам</a>
		</div>
	</div>
</div>