<div class="right_advert_head cl">
	<div class="lf fl"></div>
	<div class="right_advert_title fl"><span><?php echo $this->lang->translate("ExpoAdvert");?></span></div>
	<div class="rf fl"></div>
</div>
<div class="right_advert_content_box cl">
	<div class="right_advert_one_row cl">
		<img src="/img/index/test.png">
		<div class="right_advert_text_box">
			<a href="#">Пресс-релиз выставки «Мир детства и школы»</a>
			<span class="text cl">28.07.2010</span>
		</div>
	</div>
	<div align="center" style="padding: 5px;">
		<a href="#"><?php echo $this->lang->translate("add an ad");?></a>&nbsp;|&nbsp;<a href="#"><?php echo $this->lang->translate("become a partner");?></a>
	</div>
</div>