<?php
	$item = $this->data;
	$regions = Zend_Registry::get("regions".Tools_Events::$cacheSuffix['id']);
	$countries = Zend_Registry::get("countries".Tools_Events::$cacheSuffix['id']);
	$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
	//$categories = Zend_Registry::get("categories".Tools_Events::$cacheSuffix['id']);
	$l = DEFAULT_LANG_CODE;
	$link = '/'.$l.'/';
?>
<div class="all_companies_card_content_box cl">
<div class="companies_card_crumbs cl">
	<?php $link.='companies/search/'; $name=$this->lang->translate('Companies');?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>&nbsp;&rarr;&nbsp;
	<?php $link.='region-'.$regions[$item['regions_id']]['alias'].'/'; $name=$regions[$item['regions_id']]['name'];?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>&nbsp;&rarr;&nbsp;
	<?php $link.='country-'.$countries[$item['regions_id']][$item['countries_id']]['alias'].'/'; $name=$countries[$item['regions_id']][$item['countries_id']]['name'];?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>&nbsp;&rarr;&nbsp;
	<?php $link.='city-'.$cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['alias'].'/'; $name=$cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name'];?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>&nbsp;&rarr;&nbsp;
	<?php $link='/'.$l.'/companies/card/'.$item['id'].'-'.Tools_View::getUrlAlias($item['name'], true).'/'; $name=$item['name']; ?>
	<a href="<?php echo $link;?>"><?php echo $name;?></a>
	<?php $this->data['link'] = $link; ?>
</div>
<div class="companies_card_desc_box cl">
	<div class="left_col fl">

		<div class="companies_card_title_box cl">
			<span><?php  echo $item['name'];?></span>
		</div>
		<div class="companies_card_main_info cb">
			<div class="companies_card_info_img fl">
				<?php if($item['logo']){ ?>
					<img src="http://admin.expopromoter.com/data/images/companies/<?php echo $item['id'];?>/logo.jpg"/>
				<?php } ?>
			</div>
			<div class="companies_card_info fl">
				<div class="text fl"><?php echo $this->lang->translate('Address'); ?>:</div>
				<div class="contact fl">
					<div class="place cl">&nbsp;
<?php
	echo
		$countries[$item['regions_id']][$item['countries_id']]['name']
		.', '.
		$cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name'];
?>
					</div>
					<div class="address cl">&nbsp;<?php echo $item['adress'];?></div>
				</div>
				<div class="clr"></div>
				<div class="text fl"><?php echo $this->lang->translate('Phone'); ?>:</div>
				<div class="contact fl">
					<div class="address cl">&nbsp;<?php echo $item['phone'];?></div>
				</div>
				<div class="clr"></div>
				<div class="text fl"><?php echo $this->lang->translate('Fax'); ?>:</div>
				<div class="contact fl">
					<div class="address cl">&nbsp;<?php echo $item['fax'];?></div>
				</div>
			</div>
		</div>
	</div>

	<div class="right_col fl">
		<div class="companies_card_outer cl">
			<div class="rc_t"><div class="rc_r"><div class="rc_b"><div class="rc_l">
				<div class="rc_tl"><div class="rc_tr"><div class="rc_br"><div class="rc_bl">
					<div class="companies_card_inner cl">
						<div class="companies_card_right_lnk_row cl" style="margin-top: 0px;">
							<div class="companies_card_send_msg_ico fl"></div>
							<a href="#">Отправить</a>
						</div>
						<div class="companies_card_right_lnk_row cl">
							<div class="companies_card_star_ico fl"></div>
							<a href="#">В избранное</a>
						</div>
						<div class="companies_card_right_lnk_row cl">
							<div class="companies_card_map_ico fl"></div>
							<a href="#">Посмотреть на карте</a>
						</div>
					</div>
				</div></div></div></div>
			</div></div></div></div>
		</div>
	</div>
</div>
<div class="companies_card_something cl">
	<div class="left_border fl"></div>
	<div class="body_center fl">
		<a href="#">Пожаловаться администрации</a>
		<?php /* <span>Просмотров: 17</span> */ ?>
	</div>
	<div class="right_border fl"></div>
</div>


<div class="card_tabs_box cl">
<?php /*
<div class="tabs cl">
	<div class="tab current fl">
		<div class="tab_left fl"></div>
		<div class="tab_center fl">Описание</div>
		<div class="tab_right fl"></div>
	</div>
	<div class="tab fl">
		<div class="tab_left fl"></div>
		<div class="tab_center fl">Новости/Пресс-релизы</div>
		<div class="tab_right fl"></div>
	</div>
	<div class="tab fl">
		<div class="tab_left fl"></div>
		<div class="tab_center fl">Товары и услуги</div>
		<div class="tab_right fl"></div>
	</div>
	<div class="tab fl">
		<div class="tab_left fl"></div>
		<div class="tab_center fl">Участие в выставках</div>
		<div class="tab_right fl"></div>
	</div>
	<div class="tab fl">
		<div class="tab_left fl"></div>
		<div class="tab_center fl">Сотрудники</div>
		<div class="tab_right fl"></div>
	</div>
	<div class="tab fl">
		<div class="tab_left fl"></div>
		<div class="tab_center fl">Файлы</div>
		<div class="tab_right fl"></div>
	</div>
</div>
 */ ?>
<div class="card_tabs_body_box cl">
	<div class="cl" id="tabs">
		<ul>
<?php
	$tabsContent = '';
	$activeTabId = false;
	$tabIndex = 0;
	foreach ($this->tabsData as $tab_id=>$tab_data){
		if ($tab_data['active']) $activeTabId = $tabIndex;
		$tabsContent .= '<div class="companies_card_tab_box companies_card_'.$tab_id.'_tab" id="'.$tab_id.'">'.$this->render('/companies/tabs/'.$tab_id.'.phtml').'</div>';
		?>
		<li class="tab_title_<?php echo $tab_id;?>"><a href="#<?php echo $tab_id;?>"><?php echo $tab_data['title'];?></a></li>
		<?php
				$tabIndex++;
	}
	?>
		</ul>
		<?php echo $tabsContent; ?>
	</div>
</div>
<script type="text/javascript">
	$(function() {
		$('#tabs').tabs(<?php echo $activeTabId?'{"selected":'.$activeTabId.'}':'';?>);
	});
</script>
</div>
</div>
