/* BODY BLOCK */
<div class="companies_index_main_content_box cl">
	<div class="title cl">Выствки онлайн</div>
	<div class="lnk cl">
		<a href="index.phtml#">ИТ, Телекоммуникации, Электроника, Телерадиовещание</a><em>(1759)</em>
	</div>
	<div class="lnk cl">
		<a href="index.phtml#">Недвижимость, Финансы, Банки</a><em>(343)</em>
	</div>
	<div class="lnk cl">
		<a href="index.phtml#">Безопасность, Оборона </a><em>(549)</em>
	</div>
</div>
/*END BODY BLOCK*/


/*RIGHT BLOCK*/
<div style="width: 250px;; clear: both; float: none; margin-top: 50px;">
	<div class="banner_box cl">
		<object type="image" data="/img/companies/banner.png"></object>
	</div>
	<div class="companies_index_right_news_box cl">

		<div class="right_news_title_box cl">
			<div class="right_news_l_edge fl"></div>
			<div class="right_news_title fl">Expo-advert</div>
			<div class="right_news_r_edge fl"></div>
		</div>

		<div class="right_news_content_box cl">
			<div class="right_news_one_row cl ">
				<img src="/img/index/test2.png">
				<div class="right_news_text_box fl">
					<a href="index.phtml#">Галерея эксклюзивных стендов</a>
					<span>Стенды "под ключ" - выставка еще никогда не была такой легкой</span>
				</div>
			</div>
			<div class="right_news_one_row cl ">
				<img src="/img/index/itcatalog.png">
				<div class="right_news_text_box fl">
					<a href="index.phtml#">Конгрес "Dent-Live 2010"</a>
					<span>Стенды "под ключ" - выставка еще никогда не была такой легкой</span>
				</div>
			</div>

		</div>
	</div>
</div>

/*END RIGHT BLOCK*/


/*CENTER BLOCK*/

<div style="margin-top: 50px; width: 196px; clear: both; float: none;">
	<div class="add_comp_box">
		<a href="index.phtml#">Добавить компанию</a>
		<em>67584</em>&nbsp;<span>компаний в базе</span>
	</div>
	<div class="companies_index_center_top_comp_box cl">

		<div class="center_top_comp_title_box cl">
			<div class="center_top_comp_l_edge fl"></div>
			<div class="center_top_comp_title fl">Expo-advert</div>
			<div class="center_top_comp_r_edge fl"></div>
		</div>

		<div class="center_top_comp_content_box cl">
			<div class="center_top_comp_text_box fl">
				<a href="index.phtml#">Эфес, ООО</a>
				<span>Запорожье / Украина</span>
			</div>
			<div class="center_top_comp_text_box fl">
				<a href="index.phtml#">Дрофа-Медиа</a>
				<span>Москва / Россия</span>
			</div>
		</div>
	</div>
</div>
/* END CENTER BLOCK */