<?php
	$l = $this->lang->getLocale();
	$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
?>
<div class="exhib_cat_content_box fl">
	<div class="exhib_cat_back_lnk cl">
		<?php echo $this->lang->translate('Welcome to online trade show'); ?>
	</div>
	<div class="exhib_cat_title_box cl">
		<div class="title cl"><?php echo $this->lang->translate('Trade show Online').date(' Y'); ?></div>
	</div>
</div>
<div class="add_comp_box fr">
	<a href="#"><?php echo $this->lang->translate("Add company");?></a>
	<em><?php echo $this->statistics['company_count']?></em>&nbsp;<span><?php echo $this->lang->plural('company total', 'companies total', $this->statistics['company_count']);?></span>
</div>
<?php foreach($this->data as $showRoom){?>
<div class="sqares_outer_box cl" style="width:<?php echo $showRoom['width']+10; ?>px; height:<?php echo $showRoom['height']+10; ?>px;">
	<div class="sqares_inner_box cl" style="width:<?php echo $showRoom['width']; ?>px; height:<?php echo $showRoom['height']; ?>px;">
	<?php foreach($showRoom['places'] as $item){?>
		<div class="online_sq" style="top: <?php echo $item['top']; ?>px; left: <?php echo $item['left']; ?>px; background-image: url(/img/sqares/expo_sq_<?php echo $item['width'].'x'.$item['height']; ?>.png); width: <?php echo ($item['width']+5); ?>px; height: <?php echo ($item['height']+5); ?>px;">
			<?php if ($item['companies_id']){ $url="/".$l."/companies/card/".$item['companies_id']."-".Tools_View::getUrlAlias($item['name'], true)."/"?>
			<a target="_blank" href="<?php echo $url;?>">
			<div class="inner_online_content_box tooltip_box" style="width: <?php echo $item['width']; ?>px; height: <?php echo $item['height']; ?>px; line-height: <?php echo $item['height']; ?>px;">
				<img style="width: <?php echo $item['width']; ?>px;" src="/uploads/images/online/<?php echo $item['size']."/".$item['companies_id'];?>.jpg"/>
			</div>
			</a>
			<div class="popup_box tooltip_content">
				<div class="popup_content_box cl">
					<div class="main_top_block cl">
						<?php if ($item['logo'] != '-'){ ?>
						<img src="http://admin.expopromoter.com/data/images/companies/<?php echo $item['companies_id'];?>/logo_small.jpg">
						<?php } ?>
						<div class="main_top_info_block fl">
							<a target="_blank" href="<?php echo $url;?>"><?php echo $item['name'];?></a>
							<span><?php echo $this->lang->translate('City');?>:</span><em><?php echo $cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name_'.$l]; ?></em>
							<br/><br/><?php $d=mb_substr(strip_tags($item['description']), 0, 220, 'UTF-8'); echo $d.(mb_strlen($d, 'UTF-8')!=mb_strlen($item['description'], 'UTF-8')?'...':''); ?>
						</div>
					</div>
					<div class="bottom_link_box cl"><a target="_blank" href="<?php echo $url;?>"><?php echo $this->lang->translate('More details >>>');?></a></div>
				</div>
				<div class="tooltip_close">X</div>
			</div>
			<?php } ?>
			<div class="inner_online_sq"><?php echo $item['showrooms_order']; ?></div>
		</div>
	<?php } ?>
	</div>
</div>
<?php } ?>