<?php
	//$regions = Zend_Registry::get("regions".Tools_Events::$cacheSuffix['id']);
	$countries = Zend_Registry::get("countries".Tools_Events::$cacheSuffix['id']);
	$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
	$l = DEFAULT_LANG_CODE;
?>
<div class="companies_search_all_content_box cl">
	<div class="companies_search_back_lnk cl">
		&larr;&nbsp;<a href="/companies/online/category-<?php echo $this->jsParams['filter']['category'];?>/"><?php echo $this->lang->translate('back to online trade show plan');?></a>
	</div>
	<div class="companies_search_title_box cl">
		<div class="title cl"><?php echo $this->dataTitle.date(' Y'); ?></div>
	</div>
	<div class="search_all_companies_box cl">
	<?php
		foreach($this->data['data'] as $item){ $url="/".$l."/companies/card/".$item['id']."-".Tools_View::getUrlAlias($item['name'], true)."/";
	?>
		<div class="search_one_company_box <?php /*vip_company_bg */ ?>cl">
			<div class="one_company_title cl">
				<a href="<?php echo $url;?>">
					<?php echo $item['name'];?>
				</a>
				<?php /*
				<div class="zirochka fl"></div>
				<div class="top_ico fr"></div>
				*/ ?>
			</div>
			<div class="one_company_content_box cl">
				<div class="one_company_image_box fl">
				<?php if ($item['logo']){ ?>
				<a href="<?php echo $url;?>">
					<img src="http://admin.expopromoter.com/data/images/companies/<?php echo $item['id'];?>/logo_small.jpg"/>
				</a>
				<?php } ?>
				</div>
				<div class="one_company_text_box fl">
					<div class="one_company_place cl">
						<div class="country fl"><?php echo $countries[$item['regions_id']][$item['countries_id']]['name']; ?>,&nbsp;</div>
						<div class="city fl">&nbsp;<?php echo $cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name']; ?></div>
					</div>
					<div class="text cl">
						<?php echo Tools_View::createShortText($item['description'], 220); ?>
					</div>
					<span>Новостей: <em><?php echo $item['news_count'];?></em></span>
					<span>Товаров/услуг: <em><?php echo $item['services_count'];?></em></span>
					<?php /*
					<span> Просмотрено:<em>125</em></span>
 					*/ ?>
				</div>
			</div>
		</div>
	<?php
		}
	?>
	</div>
	<div class="paging clr">
		<?php echo Tools_View::getPages($this->requestUri, $this->data['array_pages'], 'p'); ?>
	</div>
</div>
