<?php
	//$regions = Zend_Registry::get("regions".Tools_Events::$cacheSuffix['id']);
	$countries = Zend_Registry::get("countries".Tools_Events::$cacheSuffix['id']);
	$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
	$l = $this->lang->getLocale();
?>
<div class="companies_search_all_content_box cl">
	<div class="companies_search_back_lnk cl">
		&larr;&nbsp;<a href="/companies/"><?php echo $this->lang->translate('back to categories list');?></a>
	</div>
	<div class="companies_search_title_box cl">
		<div class="title cl"><?php echo $this->lang->translate('Catalogue of companies');?></div>
	</div>
	<div class="search_all_companies_box cl">
	<?php
		foreach($this->data['data'] as $item){ $url="/".$l."/companies/card/".$item['id']."-".Tools_View::getUrlAlias($item['name'], true)."/";
	?>
		<div class="search_one_company_box <?php /*vip_company_bg */ ?>cl">
			<div class="one_company_title cl">
				<a href="<?php echo $url;?>">
					<?php echo $item['name'];?>
				</a>
				<?php /*
				<div class="zirochka fl"></div>
				<div class="top_ico fr"></div>
				*/ ?>
			</div>
			<div class="one_company_content_box cl">
				<a href="<?php echo $url;?>">
					<img src="http://admin.expopromoter.com/data/images/companies/<?php echo $item['id'];?>/logo_small.jpg"/>
				</a>
				<div class="one_company_text_box fl">
					<div class="one_company_place cl">
						<div class="country fl"><?php echo $countries[$item['regions_id']][$item['countries_id']]['name_'.$l]; ?>,&nbsp;</div>
						<div class="city fl">&nbsp;<?php echo $cities[$item['regions_id']][$item['countries_id']][$item['cities_id']]['name_'.$l]; ?></div>
					</div>
					<div class="text cl">
						<?php $d=mb_substr(strip_tags($item['description']), 0, 220, 'UTF-8'); echo $d.(mb_strlen($d, 'UTF-8')!=mb_strlen($item['description'], 'UTF-8')?'...':''); ?>
					</div>
					<?php /*
					<span>Новостей: <em>0</em></span>
					<span>Товаров/услуг: <em>1</em></span>
					<span> Просмотрено:<em>125</em></span>
 					*/ ?>
				</div>
			</div>
		</div>
	<?php
		}
	?>
	</div>
	<div class="paging clr">
		<?php echo Tools_View::getPages($this->requestUri, $this->data['array_pages'], 'p'); ?>
	</div>
</div>
