<div class="companies_search_all_content_box cl">
	<div class="companies_search_back_lnk cl">
		&larr<a href="search.phtml#">вернутся к онлайн выставке</a>
	</div>
	<div class="companies_search_title_box cl">
		<div class="title cl">Безопасность, оборона 2010</div>
		<a href="search.phtml#" style="margin-left: 0px;">Все компании </a>
		<a href="search.phtml#">Товары и услуги </a>
		<a href="search.phtml#">Новости/пресс-резизы</a>
	</div>
	<div class="search_all_companies_box cl">
		<div class="search_one_company_box vip_company_bg cl">
			<div class="one_company_title cl">
				<a href="search.phtml#">Информационно-сервисное агентство "ВИраИнфо"</a>
				<div class="zirochka fl"></div>
				<div class="top_ico fr"></div>
			</div>
			<div class="one_company_content_box cl">
				<img src="/img/companies/test_img.png">
				<div class="one_company_text_box fl">
					<div class="one_company_place cl">
						<div class="country fl">Украина,</div>
						<div class="city fl">Одесса</div>
					</div>
					<div class="text cl">
						Совместное предприятие Украинской академии аграрних наук "Агроинком" совместно с отраслевой компанией «Ассоциацией Хмелеводства» при поддержке Министерства аграрной политики Украины приглашают Вас принять участие в 17-й
					</div>
					<span>Новостей: <em>0</em></span>
					<span>Товаров/услуг: <em>1</em></span>
					<span> Просмотрено:<em>125</em></span>
				</div>
			</div>
		</div>
	</div>
</div>