<?php
	//$regions = Zend_Registry::get("regions".Tools_Events::$cacheSuffix['id']);
	$countries = Zend_Registry::get("countries".Tools_Events::$cacheSuffix['id']);
	$cities = Zend_Registry::get("cities".Tools_Events::$cacheSuffix['id']);
	$l = $this->lang->getLocale();
?>
<div class="companies_search_all_content_box cl">
	<div class="companies_search_back_lnk cl">
		&larr;&nbsp;<a href="/companies/"><?php echo $this->lang->translate('to categories list');?></a>
	</div>
	<div class="companies_search_title_box cl">
		<div class="title cl"><?php echo $this->lang->translate('Catalogue of products and services');?></div>
	</div>
	<div class="search_all_companies_box cl">
<?php
		foreach($this->data['data'] as $item){ $url= '/'.$l.'/companies/card/'.$item['companies_id'].'/'.Init_Companies_Services::$tab_name.'/card/'.$item['id'].'/';
	?>
	<div class="search_one_company_box <?php /*vip_company_bg */ ?>cl">
		<div class="one_company_title cl">
			<a href="<?php echo $url;?>">
				<?php echo $item['name'];?>
			</a>
		</div>
		<div class="one_company_content_box cl">
			<?php if ($item['photo']){ ?>
			<div class="one_company_image_box fl">
			<a href="<?php echo $url;?>">
				<img src="http://admin.expopromoter.com/data/images/companies/<?php echo $item['companies_id']; ?>/services/logo/<?php echo $item['id'];?>_small.jpg">
			</a>
			</div>
			<?php } ?>
			<div class="one_company_text_box fl">
				<div class="text cl">
					<?php echo $item['short']; ?>
				</div>
			</div>
		</div>
	</div>
	<?php
		}
	?>
	</div>
	<div class="paging clr">
		<?php echo Tools_View::getPages($this->requestUri, $this->data['array_pages'], 'p'); ?>
	</div>
</div>
