<?php
	$tabData = $this->tabsData[Init_Event_Files::$tab_name];
?>
<div class="card_files_title_box cl">
	<div class="document_info_box files_title fl"> <?php echo $this->lang->translate('Document name');?> </div>
	<div class="document_info_box files_title fr"> <?php echo $this->lang->translate('File size');?> </div>
	<div class="document_info_box files_title fr"> <?php echo $this->lang->translate('File type');?> </div>
</div>
<?php
	foreach($tabData['data'] as $item){
		$fileType = Init_Event_Files::$fileTypes[$item['content_type']];
		$fileType = $fileType?$fileType:'unknown';
?>
<div class="card_news_one_row cb">
	<div class="<?php echo $fileType; ?>_ico fl"></div>
	<a href="http://ws.expopromoter.com/file/event/?id=<?php echo $item['id']; ?>"><?php echo $item['name']; ?></a>
	<div class="document_info_box fr"><?php echo $item['size']; ?></div>
	<div class="document_info_box fr"><?php echo $fileType; ?></div>
</div>
<?php
	}
?>
