<div class="card_files_title_box cl">
	<div class="document_info_box files_title fl"> Документы </div>
	<div class="document_info_box files_title fr"> Загружен </div>
	<div class="document_info_box files_title fr"> Формат </div>
</div>
<div class="card_news_one_row cb">
	<div class="word_ico fl"></div>
	<a href="#">Пресс-релиз.doc</a>
	<div class="document_info_box fr">21.01.2010</div>
	<div class="document_info_box fr">doc</div>
</div>
<div class="card_news_one_row cb">
	<div class="excel_ico fl"></div>
	<a href="#">Таблица выставочных площадей.exl</a>
	<div class="document_info_box fr">21.01.2010</div>
	<div class="document_info_box fr">doc</div>
</div>
<div class="card_news_one_row cb">
	<div class="pdf_ico fl"></div>
	<a href="#">Пакет документов для заяки об учатсии в выставке.pdf</a>
	<div class="document_info_box fr">21.01.2010</div>
	<div class="document_info_box fr">doc</div>
</div>
<div class="card_news_one_row cb">
	<div class="pdf_ico fl"></div>
	<a href="#">Схема проезда на выставку.pdf</a>
	<div class="document_info_box fr">21.01.2010</div>
	<div class="document_info_box fr">doc</div>
</div>