<?php
	$tabData = $this->tabsData[Init_Event_News::$tab_name];
	if ($tabData['action']=='page'){
		foreach($tabData['data'] as $item){
?>
	<div class="card_one_news cl">
		<div class="card_one_news_desc fl">
			<div class="card_one_news_desc_title cl">
				<a href="<?php echo $this->data['link'].Init_Event_News::$tab_name.'/card/'.$item['id'].'/';?>">
					<?php echo $item['name']; ?>
				</a>
			</div>
			<div class="card_one_news_desc_text cl">
				<?php echo $item['preambula']; ?>
			</div>
		</div>
		<div class="card_one_news_date fl"><?php echo date('d.m.Y', strtotime($item['date_public']));?></div>
	</div>
<?php
  		}
?>
	<div class="paginator cl">
<?php
	echo Tools_View::getPages(
		array(
			'url'=>Tools_View::setUrlByTemplate(
				array(
					'url'=>$this->requestUri,
					'template'=>DEFAULT_ROUTE,
				),
				array(
					'tab'=>Init_Event_News::$tab_name,
					'tab_action'=>'page',
				)
			),
			'template'=>DEFAULT_ROUTE,
		),
		$this->tabsData[Init_Event_News::$tab_name]['array_pages'],
		'tab_id',
		array(
			'urlFunctionName'=>'setUrlByTemplate',
			'linkTag'=>array('start'=>'<div class="one_page fl">', 'end'=>'</div>'),
			'selectedTag'=>array('start'=>'<div class="one_page selected fl">', 'end'=>'</div>'),
			'first'=>false, 'prev'=>false, 'next'=>false, 'last'=>false,
		)
	);
?>
	</div>
<?php
	}
	elseif($tabData['action']=='card') {
		$item = $tabData['data'];
		$listUrl = Tools_View::setUrlByTemplate(
			array(
				'url'=>$this->requestUri,
				'template'=>DEFAULT_ROUTE
			),
			array(
				'tab'=>Init_Event_News::$tab_name,
				'tab_action'=>'page',
				'tab_id'=>'1',
			)
		);
?>
	<div class="news_full cl">
		&larr;&nbsp;<a href="<?php echo $listUrl;?>"><?php echo $this->lang->translate('back to news list');?></a>
		<div class="news_full_header cl"><?php echo $item['name'];?></div>
		<div class="news_full_content cl"><?php echo $item['content'];?></div>
	</div>
<?php
 	}
?>
