<span>Всего фотографий: 45</span>&nbsp;&nbsp;&nbsp;<span>Загружено 23.07.2010</span>
<div class="main_photo_box cl">
	<img src="/img/card/test.png">
</div>
<center><span>Демонстрации авторских работ специалистов зеленого хозяйства.</span></center>
<div class="card_photo_tab_nav cb">
	<ul style="width: 825px;">
		<li>
			<a href="#">
				<img src="/img/card/test.png">
			</a>
		</li>
		<li>
			<a href="#">
				<img src="/img/card/test.png">
			</a>
		</li>
		<li>
			<a href="#">
				<img src="/img/card/test.png">
			</a>
		</li>
		<li>
			<a href="#">
				<img src="/img/card/test.png">
			</a>
		</li>
		<li>
			<a href="#">
				<img src="/img/card/test.png">
			</a>
		</li>
		<li>
			<a href="#">
				<img src="/img/card/test.png">
			</a>
		</li>
	</ul>
</div>