<?php
	$tabData = $this->tabsData[Init_Event_Video::$tab_name];
	if ($tabData['action']=='page'){
		foreach($tabData['data'] as $item){$url = $this->data['link'].Init_Event_Video::$tab_name.'/card/'.$item['id'].'-'.Tools_View::getUrlAlias($item['title'], true).'/';
?>
	<div class="video_tab_one_row cl">
		<div class="video_tab_img">
			<a href="<?php echo $url; ?>">
				<img src="<?php echo '/uploads/video/'.date('Y/m/d/', $item['date_added']).$item['video_file_id'].'.jpg'; ?>" />
				<img class="arrow" src="/img/arrow.gif" />
			</a>
		</div>
		<div class="video_tab_desc_box fl">
			<a href="<?php echo $url; ?>">
				<?php echo $item['title'];?>
			</a><br/>
			<span><?php echo $this->lang->translate('uploaded').': '.date('d.m.Y', $item['date_added']);?></span>
			<span><?php echo $this->lang->translate('duration').': '.date('i:s', $item['duration']); ?></span>
			<div class="video_tab_desc_text cl">
				<?php echo Tools_View::createShortText($item['description'], 220); ?>
			</div>
		</div>
	</div>
<?php
		}
?>
<div class="paginator cl">
<?php
	echo Tools_View::getPages(
	array(
		'url'=>Tools_View::setUrlByTemplate(
			array(
				'url'=>$this->requestUri,
				'template'=>DEFAULT_ROUTE,
			),
			array(
				'tab'=>Init_Event_Video::$tab_name,
				'tab_action'=>'page',
			)
		),
		'template'=>DEFAULT_ROUTE,
	),
	$this->tabsData[Init_Event_Video::$tab_name]['array_pages'],
	'tab_id',
	array(
		'urlFunctionName'=>'setUrlByTemplate',
		'linkTag'=>array('start'=>'<div class="one_page fl">', 'end'=>'</div>'),
		'selectedTag'=>array('start'=>'<div class="one_page selected fl">', 'end'=>'</div>'),
		'first'=>false, 'prev'=>false, 'next'=>false, 'last'=>false,
	)
);
?>
	</div>
<?php
	}
	elseif($tabData['action']=='card') {
		$item = $tabData['data'];
		$listUrl = Tools_View::setUrlByTemplate(
			array(
				'url'=>$this->requestUri,
				'template'=>DEFAULT_ROUTE
			),
			array(
				'tab'=>Init_Event_Video::$tab_name,
				'tab_action'=>'page',
				'tab_id'=>'1',
			)
		);
?>
<div class="card_video_full cl">
	&larr;&nbsp;<a href="<?php echo $listUrl;?>"><?php echo $this->lang->translate('to videos of this trade show');?></a>
	<div class="card_video_title cl"><?php echo $item['title'];?></div>
	<object type="image" data = "/img/card/big_video_ico.png"></object>
	<div class="cl">
		<div class="video_info_box_left fl">
			<span><?php echo $this->lang->translate('uploaded').':';?></span>
			<span style="color: #333333;"> <?php echo date('d.m.Y', $item['date_added']);?></span>
			<div class="clr"></div>
		</div>
		<div class="right fr">
			<span><?php echo $this->lang->translate('duration').':';?></span>
			<span style="color: #333333;"> <?php echo date('i:s', $item['duration']);?></span>
			<div class="clr"></div>
		</div>
	</div>
	<div class="video_full_tab_text cl">
		<?php echo $item['description']; ?>
	</div>
</div>
<?php
	}
?>