<div class="video_tab_one_row cl">
	<object type="image" data="/img/card/video_ico.png">
	</object>
	<div class="video_tab_desc_box fl">
		<div class="video_tab_desc_title cl">
			<a href="#">Furniture China</a>
		</div>
		<span>Загружено 23.07.2010</span><span>Продолжительность: 4:49</span><span>Размер - 10.06 MБ</span>
		<div class="video_tab_desc_text cl">Furniture China is a professional international furniture exhibition with an excellent reputation for more than 16 years, launched in 1993.</div>
	</div>
</div>
<div class="video_tab_one_row cl">
	<object type="image" data="/img/card/video_ico.png">
	</object>
	<div class="video_tab_desc_box fl">
		<div class="video_tab_desc_title cl">
			<a href="#">Furniture China</a>
		</div>
		<span>Загружено 23.07.2010</span>Продолжительность: 4:49<span></span><span>Размер - 10.06 MБ</span>
		<div class="video_tab_desc_text cl">Furniture China is a professional international furniture exhibition with an excellent reputation for more than 16 years, launched in 1993.</div>
	</div>
</div>

<div class="card_video_full cl">
	&rarr;<a href="#">назад к списку видеороликов</a>
	<div class="card_video_title cl">Дневник выставки "Автосалон. Крым." - 2010</div>
	<object type="image" data = "/img/card/big_video_ico.png"></object>
	<div class="cl">
		<div class="video_info_box_left fl">
			<span>Выставка:</span><a href="#">Крым. Автосалон</a><div class="clr"></div>
			<span>Место проведения:</span><span style="color: #333333;">Симферополь, Украина</span><div class="clr"></div>
			<span>Дата съемки:</span><span style="color: #333333;"> 18.06.2010</span><div class="clr"></div>
		</div>
		<div class="right fr">
			<span>Загружено:</span><span style="color: #333333;">14.07.2010 </span><div class="clr"></div>
			<span>Размер:</span><span style="color: #333333;"> 21 мб</span><div class="clr"></div>
		</div>
	</div>
	<div class="video_full_tab_text cl">
		В Украине впервые состоится конференция такого уровня: в течение двух дней признанные специалисты крупнейших мировых компаний представят свое видение и отношение к наиболее обсуждаемым вопросам и новейшим тенденциям в сфере информационных и телекоммуникационных технологий.
	</div>

</div>

<div class="subscribe_box cl">
	<div class="left_border fl"></div>
	<div class="body_center fl" style="width: 500px;">
		<div class="insert_code fl">
			<span>Код для вставки:</span>
			<input type="text" style="width: 270px; margin: 8px 15px;">
			<a href="#">скопировать в буфер</a>
		</div>
	</div>
	<div class="right_border fl"></div>
</div>